export const DEFAULT_THEME = {
  light: {
    "--color-primary": "#2386d1",
    "--color-primary-content": "#ffffff",
    "--color-secondary": "#cfcfcf",
    "--color-secondary-content": "#000000",
    "--color-accent": "#81bce9",
    "--color-accent-content": "#ffffff",
    "--color-neutral": "#333357",
    "--color-neutral-content": "#ffffff",
    "--color-base-100": "#f8f9fa",
    "--color-base-200": "#ffffff",
    "--color-base-300": "#cee6f8",
    "--color-base-content": "#203656",
    "--color-info": "#01b3cb",
    "--color-info-content": "#ffffff",
    "--color-success": "#00d181",
    "--color-success-content": "#ffffff",
    "--color-warning": "#ffb700",
    "--color-warning-content": "#ffffff",
    "--color-error": "#e82f21",
    "--color-error-content": "#ffffff",
    "--main-link-color": "inherit",
  },
  dark: {
    "--color-primary": "#2386d1",
    "--color-primary-content": "#ffffff",
    "--color-secondary": "#646d82",
    "--color-secondary-content": "#ffffff",
    "--color-accent": "#88b5d8",
    "--color-accent-content": "#ffffff",
    "--color-neutral": "#000000",
    "--color-neutral-content": "#fefbf6",
    "--color-base-100": "#0c1627",
    "--color-base-200": "#263a50",
    "--color-base-300": "#36516d",
    "--color-base-content": "#ffffff",
    "--color-info": "#01b3cb",
    "--color-info-content": "#ffffff",
    "--color-success": "#00d181",
    "--color-success-content": "#ffffff",
    "--color-warning": "#ffb700",
    "--color-warning-content": "#ffffff",
    "--color-error": "#e82f21",
    "--color-error-content": "#ffffff",
    "--main-link-color": "inherit",
  },
}
